[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "ieqstar"
authors = [
    {name = "Jun Jiang", email = "jun.jiang@eonerc.rwth-aachen.de"},
]
description = "Indoor Environmental Quality – Subject Test Archive and Repository"
readme = "README.md"
requires-python = ">=3.9"
keywords = ["subject test", "data structure"]
license = "MIT License"
classifiers = [
    "Programming Language :: Python :: 3",
]
dependencies = [
    "pydantic==2.13.4",
    "pydantic_extra_types==2.11.1",
    "pytest==9.0.3"
]
dynamic = ["version"]

[tool.pytest.ini_options]
pythonpath = ["src"]
